// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {Object} QRLoginResult
 * @property {string} source
 * @property {string} key
 * @property {QRLoginStatus} status
 * @property {string} [message]
 * @property {string} [cookie]
 * @property {{ [_ in string]?: string } | null} [cookies]
 * @property {{ [_ in string]?: string } | null} [extra]
 */

/**
 * @typedef {Object} QRLoginSession
 * @property {string} source
 * @property {string} key
 * @property {string} url
 * @property {string} [image_url]
 * @property {string} [state]
 * @property {number} [expires_at]
 * @property {{ [_ in string]?: string } | null} [extra]
 */

/**
 * @readonly
 * @enum {string}
 */
export const QRLoginStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    QRLoginStatusWaiting: "waiting",
    QRLoginStatusScanned: "scanned",
    QRLoginStatusSuccess: "success",
    QRLoginStatusExpired: "expired",
    QRLoginStatusFailed: "failed",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
