import { CancellablePromise } from "@wailsio/runtime";
import * as models from "./models.js";

export function ApplyAutoStart(enabled: boolean): CancellablePromise<void>;
export function AudioServerURL(): CancellablePromise<string>;
export function CheckUpdate(): CancellablePromise<models.UpdateInfo>;
export function CloseDesktopLyric(): CancellablePromise<void>;
export function EmitMetadataChanged(): CancellablePromise<void>;
export function EnableTray(enabled: boolean): CancellablePromise<void>;
export function GetDesktopLyricConfig(): CancellablePromise<string>;
export function Greet(name: string): CancellablePromise<string>;
export function LoadConfig(): CancellablePromise<models.AppConfig>;
export function OpenImageFile(): CancellablePromise<string>;
export function OpenInExplorer(path: string): CancellablePromise<void>;
export function OpenMusicFiles(): CancellablePromise<string[]>;
export function OpenSongEditor(path: string): CancellablePromise<void>;
export function OpenMusicFolder(): CancellablePromise<string>;
export function OpenURL(u: string): CancellablePromise<void>;
export function ReadAudioFile(path: string): CancellablePromise<string>;
export function ReadCoverArt(path: string): CancellablePromise<string>;
export function ReadImageFile(path: string): CancellablePromise<string>;
export function ReadLyrics(path: string): CancellablePromise<string>;
export function ReadMetadata(path: string): CancellablePromise<models.SongMetadata>;
export function SaveConfig(config: models.AppConfig): CancellablePromise<void>;
export function ScanMusicFolder(path: string): CancellablePromise<string[]>;
export function SetCloseToTray(enabled: boolean): CancellablePromise<void>;
export function SetDesktopLyricBounds(x: number, y: number, width: number, height: number): CancellablePromise<void>;
export function SetDesktopLyricIgnoreMouseEvents(ignore: boolean): CancellablePromise<void>;
export function SetTraySongInfo(label: string): CancellablePromise<void>;
export function ShowMainWindow(): CancellablePromise<void>;
export function StopWatching(): CancellablePromise<void>;
export function ToggleDesktopLyric(enabled: boolean): CancellablePromise<void>;
export function WatchMusicFolder(path: string): CancellablePromise<void>;
export function Version(): CancellablePromise<string>;
export function OnlineSearch(keyword: string, sources: string[]): CancellablePromise<models.OnlineSong[]>;
export function OnlineLyric(song: models.OnlineSong): CancellablePromise<string>;
export function OnlineSources(): CancellablePromise<models.OnlineSource[]>;
export function OnlineVerifyKey(key: string): CancellablePromise<boolean>;
export function OnlineIsUnlocked(): CancellablePromise<boolean>;
export function OnlineDownload(song: models.OnlineSong, opts: models.OnlineDownloadOpts): CancellablePromise<models.OnlineDownloadResult>;
export function GetPlatformCookies(): CancellablePromise<Record<string, string>>;
export function SetPlatformCookies(cookies: Record<string, string>): CancellablePromise<void>;
export function SwitchSongSource(song: models.OnlineSong): CancellablePromise<models.OnlineSong>;
export function QRLoginSources(): CancellablePromise<string[]>;
export function CreateQRLogin(source: string): CancellablePromise<models.QRLoginSession>;
export function CheckQRLogin(source: string, key: string): CancellablePromise<models.QRLoginResult>;
export function OnlineRecommendPlaylists(sources: string[]): CancellablePromise<models.OnlineCollection[]>;
export function OnlineUserPlaylists(sources: string[]): CancellablePromise<models.OnlineCollection[]>;
export function OnlineSearchCollections(keyword: string, kind: string, sources: string[]): CancellablePromise<models.OnlineCollection[]>;
export function OnlineCollectionSongs(collection: models.OnlineCollection): CancellablePromise<models.OnlineSong[]>;
export function OnlineComments(song: models.OnlineSong, kind: string, page: number): CancellablePromise<models.OnlineCommentPage>;
export function OnlinePlaylistCategories(sources: string[]): CancellablePromise<models.OnlineCategorySource[]>;
export function OnlineCategoryPlaylists(source: string, categoryID: string, categoryName: string): CancellablePromise<models.OnlineCollection[]>;
export function OnlineQualityLevels(song: models.OnlineSong): CancellablePromise<string[]>;
