// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../github.com/guohuiyuan/music-lib/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyAutoStart registers or removes the application from the Windows Run registry key.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ApplyAutoStart(enabled) {
    return $Call.ByID(4069449876, enabled);
}

/**
 * AudioServerURL returns the local audio streaming server URL.
 * @returns {$CancellablePromise<string>}
 */
export function AudioServerURL() {
    return $Call.ByID(3272162535);
}

/**
 * CheckQRLogin polls the login status for a previously created QR session.
 * On success it extracts the login cookie and injects it into the shared core
 * cookie manager so subsequent searches / playback use the logged-in state; the
 * resolved cookie and its target platform are also returned via the result so
 * the frontend can persist it into config.json.
 * @param {string} source
 * @param {string} key
 * @returns {$CancellablePromise<model$0.QRLoginResult>}
 */
export function CheckQRLogin(source, key) {
    return $Call.ByID(904524293, source, key);
}

/**
 * CheckUpdate checks GitHub for a newer release. It tries the API first, then
 * the release page, then a mirror.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckUpdate() {
    return $Call.ByID(586574094);
}

/**
 * CloseDesktopLyric closes and destroys the desktop lyric window.
 * @returns {$CancellablePromise<void>}
 */
export function CloseDesktopLyric() {
    return $Call.ByID(2378771400);
}

/**
 * CreateQRLogin creates a QR login session for the given platform. When the
 * upstream session does not carry a ready-made image, a PNG data URL is
 * generated locally from the QR content URL so the frontend can render it
 * directly without any extra dependency.
 * @param {string} source
 * @returns {$CancellablePromise<model$0.QRLoginSession>}
 */
export function CreateQRLogin(source) {
    return $Call.ByID(3244372127, source);
}

/**
 * EmitMetadataChanged emits an application-wide event to notify all windows that local metadata has changed.
 * @returns {$CancellablePromise<void>}
 */
export function EmitMetadataChanged() {
    return $Call.ByID(501538565);
}

/**
 * EnableTray creates or destroys the system tray icon based on the enabled flag.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function EnableTray(enabled) {
    return $Call.ByID(3432190842, enabled);
}

/**
 * GetDesktopLyricConfig returns the current desktop lyric configuration as JSON.
 * @returns {$CancellablePromise<string>}
 */
export function GetDesktopLyricConfig() {
    return $Call.ByID(3903076466);
}

/**
 * GetPlatformCookies returns the currently configured platform cookies.
 * @returns {$CancellablePromise<{ [_ in string]?: string } | null>}
 */
export function GetPlatformCookies() {
    return $Call.ByID(568707775);
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * LoadConfig loads the application config from disk.
 * @returns {$CancellablePromise<$models.AppConfig>}
 */
export function LoadConfig() {
    return $Call.ByID(2822453907);
}

/**
 * OnlineCollectionSongs returns the songs contained in a playlist or album.
 * @param {$models.OnlineCollection} col
 * @returns {$CancellablePromise<$models.OnlineSong[] | null>}
 */
export function OnlineCollectionSongs(col) {
    return $Call.ByID(1856589160, col);
}

/**
 * OnlineDownload downloads an online song to disk according to the options.
 * It requires the download feature to be unlocked via OnlineVerifyKey.
 * @param {$models.OnlineSong} song
 * @param {$models.OnlineDownloadOpts} opts
 * @returns {$CancellablePromise<$models.OnlineDownloadResult | null>}
 */
export function OnlineDownload(song, opts) {
    return $Call.ByID(440481330, song, opts);
}

/**
 * OnlineIsUnlocked reports whether downloading has been unlocked.
 * @returns {$CancellablePromise<boolean>}
 */
export function OnlineIsUnlocked() {
    return $Call.ByID(378115603);
}

/**
 * OnlineLyric returns the LRC lyrics for an online song.
 * @param {$models.OnlineSong} song
 * @returns {$CancellablePromise<string>}
 */
export function OnlineLyric(song) {
    return $Call.ByID(698690785, song);
}

/**
 * OnlineRecommendPlaylists returns daily recommended playlists aggregated from
 * the sources that support recommendations (netease / qq / kugou / kuwo).
 * @param {string[] | null} sources
 * @returns {$CancellablePromise<$models.OnlineCollection[] | null>}
 */
export function OnlineRecommendPlaylists(sources) {
    return $Call.ByID(4056511663, sources);
}

/**
 * OnlineSearch searches multiple music sources for the given keyword.
 * @param {string} keyword
 * @param {string[] | null} sources
 * @returns {$CancellablePromise<$models.OnlineSong[] | null>}
 */
export function OnlineSearch(keyword, sources) {
    return $Call.ByID(1442961098, keyword, sources);
}

/**
 * OnlineSearchCollections searches playlists or albums (kind = "playlist" | "album")
 * across the selected sources and returns a unified list of collections.
 * @param {string} keyword
 * @param {string} kind
 * @param {string[] | null} sources
 * @returns {$CancellablePromise<$models.OnlineCollection[] | null>}
 */
export function OnlineSearchCollections(keyword, kind, sources) {
    return $Call.ByID(1391770123, keyword, kind, sources);
}

/**
 * OnlineSources returns the available music sources with descriptions.
 * @returns {$CancellablePromise<$models.OnlineSource[] | null>}
 */
export function OnlineSources() {
    return $Call.ByID(1065601540);
}

/**
 * OnlineUserPlaylists returns the logged-in user's playlists (created / collected
 * / liked) from the sources that support it (netease / qq / kugou / soda). A valid
 * platform cookie must be configured via the online settings for results to appear.
 * @param {string[] | null} sources
 * @returns {$CancellablePromise<$models.OnlineCollection[] | null>}
 */
export function OnlineUserPlaylists(sources) {
    return $Call.ByID(2238323112, sources);
}

/**
 * OnlineVerifyKey checks the download key. On success it unlocks downloading
 * for the current and all future sessions.
 * @param {string} key
 * @returns {$CancellablePromise<boolean>}
 */
export function OnlineVerifyKey(key) {
    return $Call.ByID(3621322370, key);
}

/**
 * OpenImageFile opens a file dialog for selecting a background image.
 * @returns {$CancellablePromise<string>}
 */
export function OpenImageFile() {
    return $Call.ByID(1464928384);
}

/**
 * OpenInExplorer opens the file explorer and selects the given path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(path) {
    return $Call.ByID(1095611661, path);
}

/**
 * OpenMusicFiles opens a file dialog for selecting multiple music files.
 * @returns {$CancellablePromise<string[] | null>}
 */
export function OpenMusicFiles() {
    return $Call.ByID(1240281607);
}

/**
 * OpenMusicFolder opens a directory dialog for selecting a music folder.
 * @returns {$CancellablePromise<string>}
 */
export function OpenMusicFolder() {
    return $Call.ByID(3249109596);
}

/**
 * OpenSongEditor opens a dedicated editor window for the given song path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenSongEditor(path) {
    return $Call.ByID(1743082593, path);
}

/**
 * OpenURL opens the given URL in the default system browser.
 * @param {string} u
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(u) {
    return $Call.ByID(3584934946, u);
}

/**
 * QRLoginSources returns the music platforms that support QR-code login.
 * This includes WeChat login for QQ Music via the special "qq_wx" source.
 * @returns {$CancellablePromise<string[] | null>}
 */
export function QRLoginSources() {
    return $Call.ByID(1844143715);
}

/**
 * ReadAudioFile reads the raw bytes of an audio file.
 * @param {string} path
 * @returns {$CancellablePromise<string | null>}
 */
export function ReadAudioFile(path) {
    return $Call.ByID(2158280983, path);
}

/**
 * ReadCoverArt reads embedded cover art from an audio file and returns a data URL.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadCoverArt(path) {
    return $Call.ByID(3421486013, path);
}

/**
 * ReadImageFile reads an image file and returns it as a base64 data URL.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageFile(path) {
    return $Call.ByID(602909300, path);
}

/**
 * ReadLyrics reads lyrics from an audio file's LYRICS tag or a matching .lrc file.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadLyrics(path) {
    return $Call.ByID(1952854429, path);
}

/**
 * ReadMetadata reads metadata from an audio file.
 * @param {string} path
 * @returns {$CancellablePromise<$models.SongMetadata>}
 */
export function ReadMetadata(path) {
    return $Call.ByID(2027164056, path);
}

/**
 * SaveConfig persists the application config to disk.
 * @param {$models.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(3442292638, config);
}

/**
 * ScanMusicFolder scans a folder recursively for supported music files.
 * @param {string} path
 * @returns {$CancellablePromise<string[] | null>}
 */
export function ScanMusicFolder(path) {
    return $Call.ByID(2919708231, path);
}

/**
 * SetCloseToTray updates whether the close button should hide the window to tray.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseToTray(enabled) {
    return $Call.ByID(3218749592, enabled);
}

/**
 * SetDesktopLyricBounds updates the desktop lyric window bounds and persists them.
 * @param {number} x
 * @param {number} y
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopLyricBounds(x, y, width, height) {
    return $Call.ByID(3724328361, x, y, width, height);
}

/**
 * SetDesktopLyricIgnoreMouseEvents toggles mouse event ignoring for the lyric window.
 * @param {boolean} ignore
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopLyricIgnoreMouseEvents(ignore) {
    return $Call.ByID(1835474496, ignore);
}

/**
 * SetPlatformCookies stores music-platform login cookies (the go-music-dl
 * "Cookies" feature) into the shared core cookie manager so that subsequent
 * searches / downloads / playback use the logged-in state. Persistence is
 * handled by the frontend via SaveConfig (config.json); this only updates the
 * runtime cookie manager consumed by core.GetSearchFunc / GetDownloadFunc.
 * @param {{ [_ in string]?: string } | null} cookies
 * @returns {$CancellablePromise<void>}
 */
export function SetPlatformCookies(cookies) {
    return $Call.ByID(524459155, cookies);
}

/**
 * SetTraySongInfo updates the disabled "current song" label in the tray menu.
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function SetTraySongInfo(label) {
    return $Call.ByID(3528281766, label);
}

/**
 * ShowMainWindow shows and focuses the main application window.
 * @returns {$CancellablePromise<void>}
 */
export function ShowMainWindow() {
    return $Call.ByID(3189675457);
}

/**
 * StopWatching stops watching the music folder.
 * @returns {$CancellablePromise<void>}
 */
export function StopWatching() {
    return $Call.ByID(3671977832);
}

/**
 * SwitchSongSource tries to find a playable source for the given online song.
 * If the current source is already playable it returns the song unchanged;
 * otherwise it searches other sources for a matching song and returns the first
 * playable alternative (or the original song if none is found). This backs the
 * "自动选择无效音源并批量换源" feature.
 * @param {$models.OnlineSong} song
 * @returns {$CancellablePromise<$models.OnlineSong>}
 */
export function SwitchSongSource(song) {
    return $Call.ByID(2778627285, song);
}

/**
 * ToggleDesktopLyric shows or hides the desktop lyric window.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ToggleDesktopLyric(enabled) {
    return $Call.ByID(235078, enabled);
}

/**
 * Version returns the current application version.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2431199839);
}

/**
 * WatchMusicFolder watches a folder and its subfolders for changes.
 * When files are added or removed, a "folder:changed" event is emitted.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function WatchMusicFolder(path) {
    return $Call.ByID(1295624471, path);
}
