// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyAutoStart registers or removes the application from the Windows Run registry key.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ApplyAutoStart(enabled) {
    return $Call.ByID(4069449876, enabled);
}

/**
 * AudioServerURL returns the local audio streaming server URL.
 * @returns {$CancellablePromise<string>}
 */
export function AudioServerURL() {
    return $Call.ByID(3272162535);
}

/**
 * CheckUpdate checks GitHub for a newer release. It tries the API first, then
 * the release page, then a mirror.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckUpdate() {
    return $Call.ByID(586574094);
}

/**
 * EmitMetadataChanged emits an application-wide event to notify all windows that local metadata has changed.
 * @returns {$CancellablePromise<void>}
 */
export function EmitMetadataChanged() {
    return $Call.ByID(501538565);
}

/**
 * EnableTray creates or destroys the system tray icon based on the enabled flag.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function EnableTray(enabled) {
    return $Call.ByID(3432190842, enabled);
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * LoadConfig loads the application config from disk.
 * @returns {$CancellablePromise<$models.AppConfig>}
 */
export function LoadConfig() {
    return $Call.ByID(2822453907);
}

/**
 * OpenImageFile opens a file dialog for selecting a background image.
 * @returns {$CancellablePromise<string>}
 */
export function OpenImageFile() {
    return $Call.ByID(1464928384);
}

/**
 * OpenInExplorer opens the file explorer and selects the given path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(path) {
    return $Call.ByID(1095611661, path);
}

/**
 * OpenMusicFiles opens a file dialog for selecting multiple music files.
 * @returns {$CancellablePromise<string[] | null>}
 */
export function OpenMusicFiles() {
    return $Call.ByID(1240281607);
}

/**
 * OpenMusicFolder opens a directory dialog for selecting a music folder.
 * @returns {$CancellablePromise<string>}
 */
export function OpenMusicFolder() {
    return $Call.ByID(3249109596);
}

/**
 * OpenSongEditor opens a dedicated editor window for the given song path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenSongEditor(path) {
    return $Call.ByID(1743082593, path);
}

/**
 * OpenURL opens the given URL in the default system browser.
 * @param {string} u
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(u) {
    return $Call.ByID(3584934946, u);
}

/**
 * ReadAudioFile reads the raw bytes of an audio file.
 * @param {string} path
 * @returns {$CancellablePromise<string | null>}
 */
export function ReadAudioFile(path) {
    return $Call.ByID(2158280983, path);
}

/**
 * ReadCoverArt reads embedded cover art from an audio file and returns a data URL.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadCoverArt(path) {
    return $Call.ByID(3421486013, path);
}

/**
 * ReadImageFile reads an image file and returns it as a base64 data URL.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageFile(path) {
    return $Call.ByID(602909300, path);
}

/**
 * ReadLyrics reads lyrics from an audio file's LYRICS tag or a matching .lrc file.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadLyrics(path) {
    return $Call.ByID(1952854429, path);
}

/**
 * ReadMetadata reads metadata from an audio file.
 * @param {string} path
 * @returns {$CancellablePromise<$models.SongMetadata>}
 */
export function ReadMetadata(path) {
    return $Call.ByID(2027164056, path);
}

/**
 * SaveConfig persists the application config to disk.
 * @param {$models.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(3442292638, config);
}

/**
 * ScanMusicFolder scans a folder recursively for supported music files.
 * @param {string} path
 * @returns {$CancellablePromise<string[] | null>}
 */
export function ScanMusicFolder(path) {
    return $Call.ByID(2919708231, path);
}

/**
 * SetCloseToTray updates whether the close button should hide the window to tray.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetCloseToTray(enabled) {
    return $Call.ByID(3218749592, enabled);
}

/**
 * SetTraySongInfo updates the disabled "current song" label in the tray menu.
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function SetTraySongInfo(label) {
    return $Call.ByID(3528281766, label);
}

/**
 * StopWatching stops watching the music folder.
 * @returns {$CancellablePromise<void>}
 */
export function StopWatching() {
    return $Call.ByID(3671977832);
}

/**
 * Version returns the current application version.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2431199839);
}

/**
 * WatchMusicFolder watches a folder and its subfolders for changes.
 * When files are added or removed, a "folder:changed" event is emitted.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function WatchMusicFolder(path) {
    return $Call.ByID(1295624471, path);
}
