// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as App from "./app.js";
export {
    App
};

import * as $models from "./models.js";

/**
 * AppConfig represents the persisted application config.
 * @typedef {$models.AppConfig} AppConfig
 */

/**
 * ConfigDesktopLyric stores desktop lyric window and style settings.
 * @typedef {$models.ConfigDesktopLyric} ConfigDesktopLyric
 */

/**
 * ConfigLocalMetadata stores user-edited metadata overrides for a song.
 * @typedef {$models.ConfigLocalMetadata} ConfigLocalMetadata
 */

/**
 * ConfigPlayback represents the last playback state.
 * @typedef {$models.ConfigPlayback} ConfigPlayback
 */

/**
 * ConfigPlaylist represents a playlist in persisted config.
 * @typedef {$models.ConfigPlaylist} ConfigPlaylist
 */

/**
 * ConfigPlaylistSort stores sort settings for a single playlist.
 * @typedef {$models.ConfigPlaylistSort} ConfigPlaylistSort
 */

/**
 * ConfigSettings represents app settings in persisted config.
 * @typedef {$models.ConfigSettings} ConfigSettings
 */

/**
 * ConfigSong represents a song in persisted config.
 * @typedef {$models.ConfigSong} ConfigSong
 */

/**
 * ConfigWindow represents the last window bounds.
 * @typedef {$models.ConfigWindow} ConfigWindow
 */

/**
 * SongMetadata holds audio metadata for a single file.
 * @typedef {$models.SongMetadata} SongMetadata
 */

/**
 * UpdateInfo holds the result of an update check.
 * @typedef {$models.UpdateInfo} UpdateInfo
 */
