// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as App from "./app.js";
export {
    App
};

import * as $models from "./models.js";

/**
 * AppConfig represents the persisted application config.
 * @typedef {$models.AppConfig} AppConfig
 */

/**
 * ConfigDesktopLyric stores desktop lyric window and style settings.
 * @typedef {$models.ConfigDesktopLyric} ConfigDesktopLyric
 */

/**
 * ConfigLocalMetadata stores user-edited metadata overrides for a song.
 * @typedef {$models.ConfigLocalMetadata} ConfigLocalMetadata
 */

/**
 * ConfigOnlineCollection is a pinned online playlist/album persisted to config.
 * @typedef {$models.ConfigOnlineCollection} ConfigOnlineCollection
 */

/**
 * ConfigPlayback represents the last playback state.
 * @typedef {$models.ConfigPlayback} ConfigPlayback
 */

/**
 * ConfigPlaylist represents a playlist in persisted config.
 * @typedef {$models.ConfigPlaylist} ConfigPlaylist
 */

/**
 * ConfigPlaylistSort stores sort settings for a single playlist.
 * @typedef {$models.ConfigPlaylistSort} ConfigPlaylistSort
 */

/**
 * ConfigSettings represents app settings in persisted config.
 * @typedef {$models.ConfigSettings} ConfigSettings
 */

/**
 * ConfigSong represents a song in persisted config.
 * @typedef {$models.ConfigSong} ConfigSong
 */

/**
 * ConfigWindow represents the last window bounds.
 * @typedef {$models.ConfigWindow} ConfigWindow
 */

/**
 * OnlineCollection is a playlist or album returned by the online music sources.
 * It is the unit that can be searched, recommended, listed as "my playlists",
 * opened to show its songs, and pinned to the sidebar.
 * @typedef {$models.OnlineCollection} OnlineCollection
 */

/**
 * OnlineDownloadOpts controls what gets downloaded for an online song.
 * @typedef {$models.OnlineDownloadOpts} OnlineDownloadOpts
 */

/**
 * OnlineDownloadResult reports where the downloaded files were written.
 * @typedef {$models.OnlineDownloadResult} OnlineDownloadResult
 */

/**
 * OnlineSong is the search result returned to the frontend.
 * @typedef {$models.OnlineSong} OnlineSong
 */

/**
 * OnlineSource describes a single music source for the UI.
 * @typedef {$models.OnlineSource} OnlineSource
 */

/**
 * SongMetadata holds audio metadata for a single file.
 * @typedef {$models.SongMetadata} SongMetadata
 */

/**
 * UpdateInfo holds the result of an update check.
 * @typedef {$models.UpdateInfo} UpdateInfo
 */
