// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as App from "./app.js";
export {
    App
};

import * as $models from "./models.js";

/**
 * AppConfig represents the persisted application config.
 * @typedef {$models.AppConfig} AppConfig
 */

/**
 * ConfigPlaylist represents a playlist in persisted config.
 * @typedef {$models.ConfigPlaylist} ConfigPlaylist
 */

/**
 * ConfigSettings represents app settings in persisted config.
 * @typedef {$models.ConfigSettings} ConfigSettings
 */

/**
 * ConfigSong represents a song in persisted config.
 * @typedef {$models.ConfigSong} ConfigSong
 */

/**
 * SongMetadata holds audio metadata for a single file.
 * @typedef {$models.SongMetadata} SongMetadata
 */
