// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig represents the persisted application config.
 * @typedef {Object} AppConfig
 * @property {ConfigPlaylist[] | null} playlists
 * @property {ConfigSettings} settings
 * @property {ConfigPlayback} playback
 * @property {ConfigWindow} window
 */

/**
 * ConfigDesktopLyric stores desktop lyric window and style settings.
 * @typedef {Object} ConfigDesktopLyric
 * @property {boolean} enabled
 * @property {number} fontSize
 * @property {string} mainColor
 * @property {string} unplayedColor
 * @property {string} shadowColor
 * @property {number} fontWeight
 * @property {string} position
 * @property {boolean} alwaysShowPlayInfo
 * @property {boolean} animation
 * @property {boolean} showYrc
 * @property {boolean} showTran
 * @property {boolean} isDoubleLine
 * @property {boolean} textBackgroundMask
 * @property {string} backgroundMaskColor
 * @property {string} fontFamily
 * @property {number} x
 * @property {number} y
 * @property {number} width
 * @property {number} height
 * @property {boolean} isLock
 */

/**
 * ConfigLocalMetadata stores user-edited metadata overrides for a song.
 * @typedef {Object} ConfigLocalMetadata
 * @property {string} title
 * @property {string} artist
 * @property {string} album
 * @property {string} cover
 * @property {string} lyrics
 * @property {string} lyricsFormat
 */

/**
 * ConfigOnlineCollection is a pinned online playlist/album persisted to config.
 * @typedef {Object} ConfigOnlineCollection
 * @property {string} id
 * @property {string} name
 * @property {string} cover
 * @property {string} source
 * @property {string} link
 * @property {string} kind
 * @property {string} creator
 * @property {number} trackCount
 * @property {string} extra
 */

/**
 * ConfigPlayback represents the last playback state.
 * @typedef {Object} ConfigPlayback
 * @property {string} playlistId
 * @property {number} songIndex
 * @property {number} time
 */

/**
 * ConfigPlaylist represents a playlist in persisted config.
 * @typedef {Object} ConfigPlaylist
 * @property {string} id
 * @property {string} name
 * @property {ConfigSong[] | null} songs
 * @property {string[] | null} folders
 */

/**
 * ConfigPlaylistSort stores sort settings for a single playlist.
 * @typedef {Object} ConfigPlaylistSort
 * @property {string} mode
 * @property {string} order
 */

/**
 * ConfigSettings represents app settings in persisted config.
 * @typedef {Object} ConfigSettings
 * @property {string} theme
 * @property {string} accentColor
 * @property {string} quality
 * @property {boolean} autoplay
 * @property {boolean} savePlaylistAndSong
 * @property {boolean} saveWindowPosition
 * @property {string} windowEffect
 * @property {string} customImagePath
 * @property {number} customImageOpacity
 * @property {number} customImageBlur
 * @property {number} songColorOpacity
 * @property {number} songColorBlur
 * @property {string} fullScreenBackground
 * @property {boolean} immersivePlayerBar
 * @property {{ [_ in string]?: string } | null} hotkeys
 * @property {boolean} checkUpdateOnStartup
 * @property {boolean} autoStart
 * @property {boolean} trayEnabled
 * @property {boolean} closeToTray
 * @property {ConfigDesktopLyric} desktopLyric
 * @property {string} selectedPlaylistId
 * @property {{ [_ in string]?: ConfigPlaylistSort } | null} playlistSorts
 * @property {{ [_ in string]?: ConfigLocalMetadata } | null} localMetadata
 * @property {{ [_ in string]?: string } | null} platformCookies
 * @property {boolean} autoSwitchInvalidSource
 * @property {ConfigOnlineCollection[] | null} pinnedOnlinePlaylists
 */

/**
 * ConfigSong represents a song in persisted config.
 * @typedef {Object} ConfigSong
 * @property {string} id
 * @property {string} path
 * @property {string} title
 * @property {string} [cover]
 * @property {SongMetadata | null} [metadata]
 */

/**
 * ConfigWindow represents the last window bounds.
 * @typedef {Object} ConfigWindow
 * @property {number} x
 * @property {number} y
 * @property {number} width
 * @property {number} height
 */

/**
 * OnlineCollection is a playlist or album returned by the online music sources.
 * It is the unit that can be searched, recommended, listed as "my playlists",
 * opened to show its songs, and pinned to the sidebar.
 * @typedef {Object} OnlineCollection
 * @property {string} id
 * @property {string} name
 * @property {string} cover
 * @property {string} source
 * @property {string} link
 * @property {string} kind - "playlist" | "album"
 * @property {string} creator
 * @property {number} trackCount
 * @property {string} extra
 */

/**
 * OnlineDownloadOpts controls what gets downloaded for an online song.
 * @typedef {Object} OnlineDownloadOpts
 * @property {string} dir
 * @property {boolean} withLyrics
 * @property {boolean} withCover
 * @property {boolean} embed
 */

/**
 * OnlineDownloadResult reports where the downloaded files were written.
 * @typedef {Object} OnlineDownloadResult
 * @property {string} path
 * @property {string} lyricPath
 * @property {string} coverPath
 * @property {string} warning
 */

/**
 * OnlineSong is the search result returned to the frontend.
 * @typedef {Object} OnlineSong
 * @property {string} id
 * @property {string} name
 * @property {string} artist
 * @property {string} album
 * @property {string} cover
 * @property {number} duration
 * @property {string} source
 * @property {string} extra
 * @property {string} link
 * @property {string} streamUrl
 */

/**
 * OnlineSource describes a single music source for the UI.
 * @typedef {Object} OnlineSource
 * @property {string} id
 * @property {string} name
 * @property {boolean} enabled
 */

/**
 * SongMetadata holds audio metadata for a single file.
 * @typedef {Object} SongMetadata
 * @property {string} title
 * @property {string} artist
 * @property {string} album
 * @property {string} genre
 * @property {string} year
 * @property {number} duration
 * @property {number} bitrate
 */

/**
 * UpdateInfo holds the result of an update check.
 * @typedef {Object} UpdateInfo
 * @property {string} currentVersion
 * @property {string} latestVersion
 * @property {boolean} hasUpdate
 * @property {string} releaseUrl
 * @property {string} lanzouUrl
 * @property {string} lanzouPassword
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
