// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig represents the persisted application config.
 * @typedef {Object} AppConfig
 * @property {ConfigPlaylist[] | null} playlists
 * @property {ConfigSettings} settings
 * @property {ConfigPlayback} playback
 * @property {ConfigWindow} window
 */

/**
 * ConfigLocalMetadata stores user-edited metadata overrides for a song.
 * @typedef {Object} ConfigLocalMetadata
 * @property {string} title
 * @property {string} artist
 * @property {string} album
 * @property {string} cover
 * @property {string} lyrics
 * @property {string} lyricsFormat
 */

/**
 * ConfigPlayback represents the last playback state.
 * @typedef {Object} ConfigPlayback
 * @property {string} playlistId
 * @property {number} songIndex
 * @property {number} time
 */

/**
 * ConfigPlaylist represents a playlist in persisted config.
 * @typedef {Object} ConfigPlaylist
 * @property {string} id
 * @property {string} name
 * @property {ConfigSong[] | null} songs
 * @property {string[] | null} folders
 */

/**
 * ConfigPlaylistSort stores sort settings for a single playlist.
 * @typedef {Object} ConfigPlaylistSort
 * @property {string} mode
 * @property {string} order
 */

/**
 * ConfigSettings represents app settings in persisted config.
 * @typedef {Object} ConfigSettings
 * @property {string} theme
 * @property {string} accentColor
 * @property {string} quality
 * @property {boolean} autoplay
 * @property {boolean} savePlaylistAndSong
 * @property {boolean} saveWindowPosition
 * @property {string} windowEffect
 * @property {string} customImagePath
 * @property {number} customImageOpacity
 * @property {number} customImageBlur
 * @property {number} songColorOpacity
 * @property {number} songColorBlur
 * @property {string} fullScreenBackground
 * @property {boolean} immersivePlayerBar
 * @property {{ [_ in string]?: string } | null} hotkeys
 * @property {boolean} checkUpdateOnStartup
 * @property {string} selectedPlaylistId
 * @property {{ [_ in string]?: ConfigPlaylistSort } | null} playlistSorts
 * @property {{ [_ in string]?: ConfigLocalMetadata } | null} localMetadata
 */

/**
 * ConfigSong represents a song in persisted config.
 * @typedef {Object} ConfigSong
 * @property {string} id
 * @property {string} path
 * @property {string} title
 * @property {SongMetadata | null} [metadata]
 */

/**
 * ConfigWindow represents the last window bounds.
 * @typedef {Object} ConfigWindow
 * @property {number} x
 * @property {number} y
 * @property {number} width
 * @property {number} height
 */

/**
 * SongMetadata holds audio metadata for a single file.
 * @typedef {Object} SongMetadata
 * @property {string} title
 * @property {string} artist
 * @property {string} album
 * @property {string} genre
 * @property {string} year
 * @property {number} duration
 * @property {number} bitrate
 */

/**
 * UpdateInfo holds the result of an update check.
 * @typedef {Object} UpdateInfo
 * @property {string} currentVersion
 * @property {string} latestVersion
 * @property {boolean} hasUpdate
 * @property {string} releaseUrl
 * @property {string} lanzouUrl
 * @property {string} lanzouPassword
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
