// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig represents the persisted application config.
 * @typedef {Object} AppConfig
 * @property {ConfigPlaylist[] | null} playlists
 * @property {ConfigSettings} settings
 */

/**
 * ConfigPlaylist represents a playlist in persisted config.
 * @typedef {Object} ConfigPlaylist
 * @property {string} id
 * @property {string} name
 * @property {ConfigSong[] | null} songs
 * @property {string[] | null} folders
 */

/**
 * ConfigSettings represents app settings in persisted config.
 * @typedef {Object} ConfigSettings
 * @property {string} theme
 * @property {string} accentColor
 * @property {string} quality
 * @property {boolean} autoplay
 * @property {string} windowEffect
 * @property {string} customImagePath
 * @property {number} customImageOpacity
 * @property {number} customImageBlur
 * @property {number} songColorOpacity
 * @property {number} songColorBlur
 */

/**
 * ConfigSong represents a song in persisted config.
 * @typedef {Object} ConfigSong
 * @property {string} id
 * @property {string} path
 * @property {string} title
 * @property {SongMetadata | null} [metadata]
 */

/**
 * SongMetadata holds audio metadata for a single file.
 * @typedef {Object} SongMetadata
 * @property {string} title
 * @property {string} artist
 * @property {string} album
 * @property {string} genre
 * @property {string} year
 * @property {number} duration
 * @property {number} bitrate
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
